broj1 = int(input("Unesi prvi broj: "))
broj2 = int(input("Unesi drugi broj: "))
broj3 = int(input ("Unesi treći broj: "))
minimum = min(broj1,broj2,broj3)
maksimum = max(broj1,broj2,broj3)
print("Najmanji broj je:", minimum)
print("Najveći broj je:", maksimum)